name: A1
run-name: A1
on: [push]
jobs:
  a1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Start
        run: echo 'running A1'
