name: B
run-name: B
on:
    workflow_run:
        #branches: ["*"]
        workflows:
            - "A"
        types:
            - completed
     
jobs:
  b1:
    uses: github.com/805tradingco/work/.github/workflows/callable.yml@callable-ref-test
