name: B
run-name: B
on:
    workflow_run:
        workflows:
            - "a1"
     
jobs:
  b1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start
        run: |
            echo 'running ${{ github.workflow }}'
            echo 'github workflow conclusion - ${{ github.event.workflow_run.conclusion }}'