name: B
run-name: B
on:
    workflow_run:
        #branches: ["*"]
        workflows:
            - "A"
        types:
            - completed
     
jobs:
  b1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/callable.yml@main
